
leafletcustomsettings.locations_settings:
  path: '/admin/config/leafletcustomsettings/locationssettings'
  defaults:
    _form: '\Drupal\leafletcustomsettings\Form\locationsSettings'
    _title: 'locationsSettings'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

