leafletcustomsettings.locations_settings:
  title: 'locationsSettings'
  route_name: leafletcustomsettings.locations_settings
  description: 'A description for the menu entry'
  parent: system.admin_config_system
  weight: 99

